/// One `torrent-get` list entry. Every argument has a default so a test only
/// spells out what it is about. Values are invented; the shape is 4.1.3's.
Map<String, dynamic> torrentJson({
  int id = 1,
  String hash = 'aaaa',
  String name = 'Debian netinst',
  int status = 4,
  double percentDone = 0.25,
  int rateDownload = 1024000,
  int rateUpload = 51200,
  int eta = 900,
  int totalSize = 4000000000,
  int sizeWhenDone = 4000000000,
  int leftUntilDone = 3000000000,
  int uploadedEver = 200000000,
  double uploadRatio = 0.2,
  int peersConnected = 12,
  int peersSendingToUs = 8,
  int peersGettingFromUs = 3,
  String downloadDir = '/downloads',
  int addedDate = 1758300000,
  List<String> labels = const <String>[],
  int queuePosition = 0,
  bool isFinished = false,
  bool isStalled = false,
  int error = 0,
  String errorString = '',
  double recheckProgress = 0,
  bool isPrivate = false,
  int activityDate = 1758303600,
  double metadataPercentComplete = 1,
  int webseedsSendingToUs = 0,
  List<Map<String, dynamic>> trackers = const <Map<String, dynamic>>[
    <String, dynamic>{
      'announce': 'http://bttracker.debian.org:6969/announce',
      'id': 0,
      'scrape': 'http://bttracker.debian.org:6969/scrape',
      'sitename': 'debian',
      'tier': 0,
    },
  ],
}) =>
    <String, dynamic>{
      'id': id,
      'hashString': hash,
      'name': name,
      'status': status,
      'percentDone': percentDone,
      'rateDownload': rateDownload,
      'rateUpload': rateUpload,
      'eta': eta,
      'totalSize': totalSize,
      'sizeWhenDone': sizeWhenDone,
      'leftUntilDone': leftUntilDone,
      'uploadedEver': uploadedEver,
      'uploadRatio': uploadRatio,
      'peersConnected': peersConnected,
      'peersSendingToUs': peersSendingToUs,
      'peersGettingFromUs': peersGettingFromUs,
      'downloadDir': downloadDir,
      'addedDate': addedDate,
      'labels': labels,
      'queuePosition': queuePosition,
      'isFinished': isFinished,
      'isStalled': isStalled,
      'error': error,
      'errorString': errorString,
      'recheckProgress': recheckProgress,
      'isPrivate': isPrivate,
      'activityDate': activityDate,
      'metadataPercentComplete': metadataPercentComplete,
      'webseedsSendingToUs': webseedsSendingToUs,
      'trackers': trackers,
    };

/// A `session-get` answer with every key the module reads, as 4.1.3 names
/// them.
Map<String, dynamic> sessionJson({
  int rpcVersion = 19,
  String encryption = 'preferred',
  bool altSpeedTimeEnabled = false,
  int altSpeedTimeDay = 127,
  int blocklistSize = 0,
}) =>
    <String, dynamic>{
      'version': '4.1.3 (838877323f)',
      'rpc-version': rpcVersion,
      'download-dir': '/downloads/complete',
      'download-dir-free-space': -1,
      'speed-limit-down': 5000,
      'speed-limit-down-enabled': false,
      'speed-limit-up': 1000,
      'speed-limit-up-enabled': true,
      'alt-speed-enabled': false,
      'alt-speed-down': 500,
      'alt-speed-up': 100,
      'alt-speed-time-enabled': altSpeedTimeEnabled,
      'alt-speed-time-begin': 540,
      'alt-speed-time-end': 1020,
      'alt-speed-time-day': altSpeedTimeDay,
      'start-added-torrents': true,
      'seedRatioLimited': false,
      'seedRatioLimit': 2.0,
      'idle-seeding-limit-enabled': false,
      'idle-seeding-limit': 30,
      'incomplete-dir-enabled': false,
      'incomplete-dir': '/downloads/incomplete',
      'rename-partial-files': true,
      'download-queue-enabled': true,
      'download-queue-size': 5,
      'default-trackers': '',
      'peer-limit-per-torrent': 50,
      'peer-limit-global': 1000,
      'encryption': encryption,
      'pex-enabled': true,
      'dht-enabled': true,
      'lpd-enabled': false,
      'blocklist-enabled': false,
      'blocklist-url': 'http://www.example.com/blocklist',
      'blocklist-size': blocklistSize,
      'peer-port': 51413,
      'peer-port-random-on-start': false,
      'port-forwarding-enabled': true,
      'utp-enabled': true,
    };

Map<String, dynamic> statsJson() => <String, dynamic>{
      'activeTorrentCount': 1,
      'pausedTorrentCount': 0,
      'torrentCount': 1,
      'downloadSpeed': 1024000,
      'uploadSpeed': 51200,
      'current-stats': <String, dynamic>{
        'uploadedBytes': 1000,
        'downloadedBytes': 4000,
        'filesAdded': 1,
        'secondsActive': 3600,
        'sessionCount': 1,
      },
      'cumulative-stats': <String, dynamic>{
        'uploadedBytes': 391807173959,
        'downloadedBytes': 252248492328,
        'filesAdded': 15673,
        'secondsActive': 9286824,
        'sessionCount': 57,
      },
    };

/// The detail fields for one torrent: a two-file torrent in a folder, one
/// peer, one tracker that has announced, one web seed.
Map<String, dynamic> detailJson({
  bool trackerSucceeded = true,
  int announceState = 1,
}) =>
    <String, dynamic>{
      'comment': 'https://www.debian.org/CD/',
      'creator': 'mktorrent 1.1',
      'isPrivate': false,
      'pieceCount': 1000,
      'pieceSize': 4000000,
      'dateCreated': 1758200000,
      'haveValid': 900000000,
      'haveUnchecked': 100000000,
      'desiredAvailable': 3000000000,
      'downloadedEver': 1050000000,
      'corruptEver': 50000000,
      'startDate': 1758303000,
      'magnetLink': 'magnet:?xt=urn:btih:aaaa&dn=Debian+netinst',
      'webseeds': <String>['https://cdimage.debian.org/'],
      'files': <Map<String, dynamic>>[
        <String, dynamic>{
          'name': 'debian/README.txt',
          'length': 1000,
          'bytesCompleted': 1000,
        },
        <String, dynamic>{
          'name': 'debian/iso/netinst.iso',
          'length': 3999999000,
          'bytesCompleted': 999999000,
        },
      ],
      'fileStats': <Map<String, dynamic>>[
        <String, dynamic>{
          'bytesCompleted': 1000,
          'wanted': true,
          'priority': 0,
        },
        <String, dynamic>{
          'bytesCompleted': 999999000,
          'wanted': true,
          'priority': 1,
        },
      ],
      'peers': <Map<String, dynamic>>[
        <String, dynamic>{
          'address': '10.0.0.5',
          'port': 51413,
          'clientName': 'qBittorrent 5.0',
          'progress': 0.5,
          'rateToClient': 100000,
          'rateToPeer': 2000,
          'isEncrypted': true,
          'flagStr': 'DEI',
        },
      ],
      'trackerStats': <Map<String, dynamic>>[
        <String, dynamic>{
          'host': 'bttracker.debian.org:6969',
          'sitename': 'debian',
          'announce': 'http://bttracker.debian.org:6969/announce',
          'tier': 0,
          'announceState': announceState,
          'hasAnnounced': true,
          'lastAnnounceSucceeded': trackerSucceeded,
          'lastAnnounceResult': trackerSucceeded ? 'Success' : 'Timed out',
          'lastAnnounceTime': 1758303000,
          'lastAnnouncePeerCount': 40,
          'nextAnnounceTime': 1758304800,
          'hasScraped': true,
          'lastScrapeSucceeded': true,
          'lastScrapeResult': '',
          'lastScrapeTime': 1758302000,
          'seederCount': 300,
          'leecherCount': 20,
          'downloadCount': 5000,
          'isBackup': false,
        },
      ],
    };
