openapi: 3.0.1
info:
  title: Sonarr API Implementation Status
  description: Mapping of v3.yaml specification endpoints to their Dart implementations in services/service_sonarr/lib/src/sonarr_api.dart
  version: 1.0.0

paths:
  /api:
    get:
      methodName: getApiInfo
      status: implemented
  /login:
    post:
      methodName: login
      status: implemented
  /logout:
    get:
      methodName: logout
      status: implemented

  /api/v3/autotagging:
    get:
      methodName: getAutoTagging
      status: implemented
    post:
      methodName: createAutoTagging
      status: implemented
  /api/v3/autotagging/schema:
    get:
      methodName: getAutoTaggingSchema
      status: implemented
  /api/v3/autotagging/{id}:
    put:
      methodName: updateAutoTagging
      status: implemented
    delete:
      methodName: deleteAutoTagging
      status: implemented

  /api/v3/blocklist:
    get:
      methodName: getBlocklist
      status: implemented
  /api/v3/blocklist/bulk:
    delete:
      methodName: deleteBlocklistBulk
      status: implemented
  /api/v3/blocklist/{id}:
    delete:
      methodName: deleteBlocklistItem
      status: implemented

  /api/v3/calendar:
    get:
      methodName: getCalendar
      status: implemented
  /api/v3/calendar/{id}:
    get:
      methodName: getCalendarById
      status: implemented

  /api/v3/command:
    get:
      methodName: getCommands
      status: implemented
    post:
      methodName: runCommand
      status: implemented
  /api/v3/command/{id}:
    get:
      methodName: getCommandStatus
      status: implemented
    delete:
      methodName: abortCommand
      status: implemented

  /api/v3/config/downloadclient:
    get:
      methodName: getDownloadClientConfig
      status: implemented
  /api/v3/config/downloadclient/{id}:
    put:
      methodName: updateDownloadClientConfig
      status: implemented
  /api/v3/config/host:
    get:
      methodName: getHostConfig
      status: implemented
  /api/v3/config/host/{id}:
    put:
      methodName: updateHostConfig
      status: implemented
  /api/v3/config/importlist:
    get:
      methodName: getImportListConfig
      status: implemented
  /api/v3/config/importlist/{id}:
    put:
      methodName: updateImportListConfig
      status: implemented
  /api/v3/config/indexer:
    get:
      methodName: getIndexerConfig
      status: implemented
  /api/v3/config/indexer/{id}:
    put:
      methodName: updateIndexerConfig
      status: implemented
  /api/v3/config/mediamanagement:
    get:
      methodName: getMediaManagementConfig
      status: implemented
  /api/v3/config/mediamanagement/{id}:
    put:
      methodName: updateMediaManagementConfig
      status: implemented
  /api/v3/config/naming:
    get:
      methodName: getNamingConfig
      status: implemented
  /api/v3/config/naming/{id}:
    put:
      methodName: updateNamingConfig
      status: implemented
  /api/v3/config/naming/examples:
    get:
      methodName: getNamingExamples
      status: implemented
  /api/v3/config/ui:
    get:
      methodName: getUiConfig
      status: implemented
  /api/v3/config/ui/{id}:
    put:
      methodName: updateUiConfig
      status: implemented

  /api/v3/customfilter:
    get:
      methodName: getCustomFilters
      status: implemented
    post:
      methodName: createCustomFilter
      status: implemented
  /api/v3/customfilter/{id}:
    put:
      methodName: updateCustomFilter
      status: implemented
    delete:
      methodName: deleteCustomFilter
      status: implemented

  /api/v3/customformat:
    get:
      methodName: getCustomFormats
      status: implemented
    post:
      methodName: createCustomFormat
      status: implemented
  /api/v3/customformat/bulk:
    put:
      methodName: updateCustomFormatBulk
      status: implemented
  /api/v3/customformat/schema:
    get:
      methodName: getCustomFormatSchema
      status: implemented
  /api/v3/customformat/{id}:
    put:
      methodName: updateCustomFormat
      status: implemented
    delete:
      methodName: deleteCustomFormat
      status: implemented

  /api/v3/delayprofile:
    get:
      methodName: getDelayProfiles
      status: implemented
    post:
      methodName: createDelayProfile
      status: implemented
  /api/v3/delayprofile/reorder/{id}:
    put:
      methodName: reorderDelayProfiles
      status: implemented
  /api/v3/delayprofile/{id}:
    put:
      methodName: updateDelayProfile
      status: implemented
    delete:
      methodName: deleteDelayProfile
      status: implemented

  /api/v3/diskspace:
    get:
      methodName: getDiskSpace
      status: implemented

  /api/v3/downloadclient:
    get:
      methodName: getDownloadClients
      status: implemented
    post:
      methodName: createDownloadClient
      status: implemented
  /api/v3/downloadclient/bulk:
    put:
      methodName: updateDownloadClientsBulk
      status: implemented
  /api/v3/downloadclient/schema:
    get:
      methodName: getDownloadClientSchema
      status: implemented
  /api/v3/downloadclient/test:
    post:
      methodName: testDownloadClient
      status: implemented
  /api/v3/downloadclient/testall:
    post:
      methodName: testAllDownloadClients
      status: implemented
  /api/v3/downloadclient/action/{name}:
    post:
      methodName: performDownloadClientAction
      status: implemented
  /api/v3/downloadclient/{id}:
    put:
      methodName: updateDownloadClient
      status: implemented
    delete:
      methodName: deleteDownloadClient
      status: implemented

  /api/v3/episode:
    get:
      methodName: getEpisodes
      status: implemented
  /api/v3/episode/monitor:
    put:
      methodName: updateEpisodeMonitor
      status: implemented
  /api/v3/episode/{id}:
    get:
      methodName: getEpisodeById
      status: implemented
    put:
      methodName: updateEpisode
      status: implemented

  /api/v3/episodefile:
    get:
      methodName: getEpisodeFiles
      status: implemented
  /api/v3/episodefile/bulk:
    put:
      methodName: updateEpisodeFilesBulk
      status: implemented
    delete:
      methodName: deleteEpisodeFilesBulk
      status: implemented
  /api/v3/episodefile/editor:
    post:
      methodName: editEpisodeFile
      status: implemented
  /api/v3/episodefile/{id}:
    get:
      methodName: getEpisodeFileById
      status: implemented
    put:
      methodName: updateEpisodeFile
      status: implemented
    delete:
      methodName: deleteEpisodeFile
      status: implemented

  /api/v3/filesystem:
    get:
      methodName: getFileSystem
      status: implemented
  /api/v3/filesystem/type:
    get:
      methodName: getFileSystemType
      status: implemented
  /api/v3/filesystem/mediafiles:
    get:
      methodName: getFileSystemMediaFiles
      status: implemented

  /api/v3/health:
    get:
      methodName: getHealth
      status: implemented

  /api/v3/history:
    get:
      methodName: getHistory
      status: implemented
  /api/v3/history/failed/{id}:
    post:
      methodName: failHistoryItem
      status: implemented
  /api/v3/history/series:
    get:
      methodName: getHistoryBySeries
      status: implemented
  /api/v3/history/since:
    get:
      methodName: getHistorySince
      status: implemented

  /api/v3/importlist:
    get:
      methodName: getImportLists
      status: implemented
    post:
      methodName: createImportList
      status: implemented
  /api/v3/importlist/bulk:
    put:
      methodName: updateImportListsBulk
      status: implemented
  /api/v3/importlist/schema:
    get:
      methodName: getImportListSchema
      status: implemented
  /api/v3/importlist/test:
    post:
      methodName: testImportList
      status: implemented
  /api/v3/importlist/testall:
    post:
      methodName: testAllImportLists
      status: implemented
  /api/v3/importlist/action/{name}:
    post:
      methodName: performImportListAction
      status: implemented
  /api/v3/importlist/{id}:
    put:
      methodName: updateImportList
      status: implemented
    delete:
      methodName: deleteImportList
      status: implemented

  /api/v3/importlistexclusion:
    get:
      methodName: getImportListExclusions
      status: implemented
    post:
      methodName: createImportListExclusion
      status: implemented
  /api/v3/importlistexclusion/bulk:
    delete:
      methodName: deleteImportListExclusionsBulk
      status: implemented
  /api/v3/importlistexclusion/paged:
    get:
      methodName: getImportListExclusionsPaged
      status: implemented
  /api/v3/importlistexclusion/{id}:
    put:
      methodName: updateImportListExclusion
      status: implemented
    delete:
      methodName: deleteImportListExclusion
      status: implemented

  /api/v3/indexer:
    get:
      methodName: getIndexers
      status: implemented
    post:
      methodName: createIndexer
      status: implemented
  /api/v3/indexer/bulk:
    put:
      methodName: updateIndexersBulk
      status: implemented
  /api/v3/indexer/schema:
    get:
      methodName: getIndexerSchema
      status: implemented
  /api/v3/indexer/test:
    post:
      methodName: testIndexer
      status: implemented
  /api/v3/indexer/testall:
    post:
      methodName: testAllIndexers
      status: implemented
  /api/v3/indexer/action/{name}:
    post:
      methodName: performIndexerAction
      status: implemented
  /api/v3/indexer/{id}:
    put:
      methodName: updateIndexer
      status: implemented
    delete:
      methodName: deleteIndexer
      status: implemented

  /api/v3/indexerflag:
    get:
      methodName: getIndexerFlags
      status: implemented

  /api/v3/language:
    get:
      methodName: getLanguages
      status: implemented
  /api/v3/language/{id}:
    get:
      methodName: getLanguageById
      status: implemented

  /api/v3/languageprofile:
    get:
      methodName: getLanguageProfiles
      status: implemented
    post:
      methodName: createLanguageProfile
      status: implemented
  /api/v3/languageprofile/schema:
    get:
      methodName: getLanguageProfileSchema
      status: implemented
  /api/v3/languageprofile/{id}:
    put:
      methodName: updateLanguageProfile
      status: implemented
    delete:
      methodName: deleteLanguageProfile
      status: implemented

  /api/v3/localization:
    get:
      methodName: getLocalizations
      status: implemented
  /api/v3/localization/language:
    get:
      methodName: getLocalizationLanguage
      status: implemented
  /api/v3/localization/{id}:
    get:
      methodName: getLocalizationById
      status: implemented

  /api/v3/log:
    get:
      methodName: getLogs
      status: implemented
  /api/v3/log/file:
    get:
      methodName: getLogFiles
      status: implemented
  /api/v3/log/file/update:
    get:
      methodName: getLogFileUpdates
      status: implemented
  /api/v3/log/file/{filename}:
    get:
      methodName: getLogFileContent
      status: implemented
    delete:
      methodName: deleteLogFile
      status: implemented
  /api/v3/log/file/update/{filename}:
    get:
      methodName: getLogFileUpdateContent
      status: implemented

  /api/v3/manualimport:
    get:
      methodName: getManualImport
      status: implemented

  /api/v3/mediacover/{seriesId}/{filename}:
    get:
      methodName: posterUrl
      status: implemented

  /api/v3/metadata:
    get:
      methodName: getMetadataConfigs
      status: implemented
    post:
      methodName: createMetadataConfig
      status: implemented
  /api/v3/metadata/schema:
    get:
      methodName: getMetadataSchema
      status: implemented
  /api/v3/metadata/test:
    post:
      methodName: testMetadataConfig
      status: implemented
  /api/v3/metadata/testall:
    post:
      methodName: testAllMetadataConfigs
      status: implemented
  /api/v3/metadata/action/{name}:
    post:
      methodName: performMetadataAction
      status: implemented
  /api/v3/metadata/{id}:
    put:
      methodName: updateMetadataConfig
      status: implemented
    delete:
      methodName: deleteMetadataConfig
      status: implemented

  /api/v3/notification:
    get:
      methodName: getNotifications
      status: implemented
    post:
      methodName: createNotification
      status: implemented
  /api/v3/notification/schema:
    get:
      methodName: getNotificationSchema
      status: implemented
  /api/v3/notification/test:
    post:
      methodName: testNotification
      status: implemented
  /api/v3/notification/testall:
    post:
      methodName: testAllNotifications
      status: implemented
  /api/v3/notification/action/{name}:
    post:
      methodName: performNotificationAction
      status: implemented
  /api/v3/notification/{id}:
    put:
      methodName: updateNotification
      status: implemented
    delete:
      methodName: deleteNotification
      status: implemented

  /api/v3/parse:
    get:
      methodName: parseTitleOrPath
      status: implemented

  /api/v3/qualitydefinition:
    get:
      methodName: getQualityDefinitions
      status: implemented
  /api/v3/qualitydefinition/limits:
    get:
      methodName: getQualityDefinitionLimits
      status: implemented
  /api/v3/qualitydefinition/update:
    put:
      methodName: updateQualityDefinitions
      status: implemented
  /api/v3/qualitydefinition/{id}:
    get:
      methodName: getQualityDefinitionById
      status: implemented
    put:
      methodName: updateQualityDefinition
      status: implemented

  /api/v3/qualityprofile:
    get:
      methodName: getQualityProfiles
      status: implemented
    post:
      methodName: createQualityProfile
      status: implemented
  /api/v3/qualityprofile/schema:
    get:
      methodName: getQualityProfileSchema
      status: implemented
  /api/v3/qualityprofile/{id}:
    get:
      methodName: getQualityProfileById
      status: implemented
    put:
      methodName: updateQualityProfile
      status: implemented
    delete:
      methodName: deleteQualityProfile
      status: implemented

  /api/v3/queue:
    get:
      methodName: getQueue
      status: implemented
  /api/v3/queue/bulk:
    put:
      methodName: updateQueueBulk
      status: implemented
    delete:
      methodName: deleteQueueBulk
      status: implemented
  /api/v3/queue/details:
    get:
      methodName: getQueueDetails
      status: implemented
  /api/v3/queue/status:
    get:
      methodName: getQueueStatus
      status: implemented
  /api/v3/queue/grab/{id}:
    post:
      methodName: grabQueueItem
      status: implemented
  /api/v3/queue/grab/bulk:
    post:
      methodName: grabQueueBulk
      status: implemented
  /api/v3/queue/{id}:
    delete:
      methodName: deleteQueueItem
      status: implemented

  /api/v3/release:
    get:
      methodName: getReleases
      status: implemented
    post:
      methodName: downloadRelease
      status: implemented
  /api/v3/release/push:
    post:
      methodName: pushRelease
      status: implemented

  /api/v3/releaseprofile:
    get:
      methodName: getReleaseProfiles
      status: implemented
    post:
      methodName: createReleaseProfile
      status: implemented
  /api/v3/releaseprofile/{id}:
    get:
      methodName: getReleaseProfileById
      status: implemented
    put:
      methodName: updateReleaseProfile
      status: implemented
    delete:
      methodName: deleteReleaseProfile
      status: implemented

  /api/v3/remotepathmapping:
    get:
      methodName: getRemotePathMappings
      status: implemented
    post:
      methodName: createRemotePathMapping
      status: implemented
  /api/v3/remotepathmapping/{id}:
    get:
      methodName: getRemotePathMappingById
      status: implemented
    put:
      methodName: updateRemotePathMapping
      status: implemented
    delete:
      methodName: deleteRemotePathMapping
      status: implemented

  /api/v3/rename:
    get:
      methodName: getRenamePreview
      status: implemented

  /api/v3/rootfolder:
    get:
      methodName: getRootFolders
      status: implemented
  /api/v3/rootfolder/{id}:
    delete:
      methodName: deleteRootFolder
      status: implemented

  /api/v3/seasonpass:
    post:
      methodName: updateSeasonPass
      status: implemented

  /api/v3/series:
    get:
      methodName: getSeries
      status: implemented
    post:
      methodName: addSeries
      status: implemented
  /api/v3/series/editor:
    put:
      methodName: updateSeriesBulk
      status: implemented
    delete:
      methodName: deleteSeriesBulk
      status: implemented
  /api/v3/series/import:
    get:
      methodName: getSeriesImportOptions
      status: implemented
    post:
      methodName: importSeries
      status: implemented
  /api/v3/series/lookup:
    get:
      methodName: lookupSeries
      status: implemented
  /api/v3/series/{id}:
    get:
      methodName: getSeriesById
      status: implemented
    put:
      methodName: updateSeriesRaw
      status: implemented
    delete:
      methodName: deleteSeries
      status: implemented
  /api/v3/series/{id}/folder:
    get:
      methodName: getSeriesFolder
      status: implemented

  /api/v3/system/backup:
    get:
      methodName: getBackups
      status: implemented
  /api/v3/system/backup/{id}:
    delete:
      methodName: deleteBackup
      status: implemented
  /api/v3/system/backup/restore/{id}:
    post:
      methodName: restoreBackup
      status: implemented
  /api/v3/system/backup/restore/upload:
    post:
      methodName: uploadAndRestoreBackup
      status: implemented
  /api/v3/system/restart:
    post:
      methodName: restartSonarr
      status: implemented
  /api/v3/system/shutdown:
    post:
      methodName: shutdownSonarr
      status: implemented
  /api/v3/system/status:
    get:
      methodName: getSystemStatus
      status: implemented
  /api/v3/system/routes:
    get:
      methodName: getSystemRoutes
      status: implemented
  /api/v3/system/routes/duplicate:
    get:
      methodName: getSystemRoutesDuplicate
      status: implemented
  /api/v3/system/task:
    get:
      methodName: getTasks
      status: implemented
  /api/v3/system/task/{id}:
    get:
      methodName: getTaskById
      status: implemented

  /api/v3/tag:
    get:
      methodName: getTags
      status: implemented
    post:
      methodName: createTag
      status: implemented
  /api/v3/tag/detail:
    get:
      methodName: getTagDetails
      status: implemented
  /api/v3/tag/detail/{id}:
    get:
      methodName: getTagDetailsById
      status: implemented
  /api/v3/tag/{id}:
    get:
      methodName: getTagById
      status: implemented
    put:
      methodName: updateTag
      status: implemented
    delete:
      methodName: deleteTag
      status: implemented

  /api/v3/update:
    get:
      methodName: getUpdates
      status: implemented

  /api/v3/wanted/cutoff:
    get:
      methodName: getWantedCutoff
      status: implemented
  /api/v3/wanted/cutoff/{id}:
    delete:
      methodName: deleteWantedCutoff
      status: implemented
  /api/v3/wanted/missing:
    get:
      methodName: getWantedMissing
      status: implemented
  /api/v3/wanted/missing/{id}:
    delete:
      methodName: deleteWantedMissing
      status: implemented
