name: dynamic_color
description: A dummy package to override dynamic_color and redirect it to dynamic_system_colors to avoid Android plugin compilation errors with duplicate classes.
version: 1.8.1
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ^3.27.0

dependencies:
  dynamic_system_colors: ^1.9.0
  flutter:
    sdk: flutter
